// Generated by Rcpp::compileAttributes() - do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// random_batch_cpp
NumericVector random_batch_cpp(int seed, int count, double min_val, double max_val);
RcppExport SEXP _jigsawR_random_batch_cpp(SEXP seedSEXP, SEXP countSEXP, SEXP min_valSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type min_val(min_valSEXP);
    Rcpp::traits::input_parameter< double >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(random_batch_cpp(seed, count, min_val, max_val));
    return rcpp_result_gen;
END_RCPP
}
// bezier_batch_cpp
NumericMatrix bezier_batch_cpp(NumericVector p0, NumericVector cp1, NumericVector cp2, NumericVector p1, int n_points);
RcppExport SEXP _jigsawR_bezier_batch_cpp(SEXP p0SEXP, SEXP cp1SEXP, SEXP cp2SEXP, SEXP p1SEXP, SEXP n_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cp1(cp1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cp2(cp2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(bezier_batch_cpp(p0, cp1, cp2, p1, n_points));
    return rcpp_result_gen;
END_RCPP
}
// svg_translate_cpp
std::string svg_translate_cpp(std::string path_string, double dx, double dy);
RcppExport SEXP _jigsawR_svg_translate_cpp(SEXP path_stringSEXP, SEXP dxSEXP, SEXP dySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path_string(path_stringSEXP);
    Rcpp::traits::input_parameter< double >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< double >::type dy(dySEXP);
    rcpp_result_gen = Rcpp::wrap(svg_translate_cpp(path_string, dx, dy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jigsawR_random_batch_cpp", (DL_FUNC) &_jigsawR_random_batch_cpp, 4},
    {"_jigsawR_bezier_batch_cpp", (DL_FUNC) &_jigsawR_bezier_batch_cpp, 5},
    {"_jigsawR_svg_translate_cpp", (DL_FUNC) &_jigsawR_svg_translate_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_jigsawR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
